<?php

namespace AppBundle\Repository;

/**
 * TypeEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEventRepository extends \Doctrine\ORM\EntityRepository
{
}
